server:
  port: 8081
  forward-headers-strategy: framework

spring:
  web:
    resources:
      add-mappings: false
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/parkease_auth
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

          github:
            client-id: YOUR_GITHUB_CLIENT_ID
            client-secret: YOUR_GITHUB_CLIENT_SECRET
            scope:
              - user:email
              - read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

jwt:
  secret: ${JWT_SECRET}
  expiry: 86400000

otp:
  expiry-minutes: 10
  resend-window-seconds: 30
  max-attempts: 5
  lockout-duration-hours: 2
  max-verify-attempts: 3

resend:
  api-key: ${RESEND_API_KEY}
  from-email: ${RESEND_FROM_EMAIL:reply@smartmeeter.online}
  from-name: ${RESEND_FROM_NAME:ParkEase}

# OAuth2 Frontend Callback Configuration
oauth2:
  frontend:
    callback-url: ${OAUTH2_FRONTEND_CALLBACK_URL:http://localhost:5174/oauth/callback}



admin:
  seed-email: ${ADMIN_SEED_EMAIL:admin@parkease.com}
  seed-password: ${ADMIN_SEED_PASSWORD:Admin@ParkEase123}
  seed-name: ${ADMIN_SEED_NAME:Super Admin}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

debug: true

