server:
  port: 8080



spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: parkinglot-service
          uri: lb://parkinglot-service
          predicates:
            - Path=/api/v1/lots/**

        - id: spot-service
          uri: lb://spot-service
          predicates:
            - Path=/api/v1/spots/**

        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/v1/bookings/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payments/**

        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/v1/vehicles/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**

        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/v1/analytics/**

cors:
  allowed-origins:
    - http://localhost:3000      # React CRA
    - http://localhost:5173
    - http://localhost:5175       
    - http://localhost:5174      # Vite (alt)
    - http://127.0.0.1:3000      # Localhost alternative
    - http://localhost:3001      # Production frontend
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true
  max-age: 3600  # Preflight cache duration in seconds


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    health:
      show-details: always