name: Deploy Auth Service

on:
  push:
    branches: [deployment]
    paths:
      - 'auth-service/**'

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy-service.yml
    with:
      service_name: auth-service
      service_port: "8081"
      service_dir: auth-service
    secrets:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}