name: Deploy config-service

on:
  push:
    branches: [main, deployment]
    paths:
      - 'config-service/**'
      - '.github/workflows/deploy-config-service.yml'

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy-service.yml
    with:
      service_name: config-service
      service_port: '8888'
      service_dir: config-service
    secrets: inherit
